In [1]:
import gym

In [2]:
env = gym.make("CartPole-v0")

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-05-18 23:22:32,003] Making new env: CartPole-v0


In [3]:
env.action_space.n

2

In [10]:
env.x_threshold

2.4

In [11]:
env.metadata

{'render.modes': ['human', 'rgb_array'], 'video.frames_per_second': 50}

In [12]:
env.state

array([ 0.00233653, -0.03720394,  0.03666514,  0.01682752])

In [21]:
env.observation_space.sample()

array([ 0.94212961,         nan,  0.07764953,         nan])

In [23]:
print env.observation_space.low
env.observation_space.low

[-2.4               -inf -0.20943951        -inf]


array([-2.4       ,        -inf, -0.20943951,        -inf])

In [24]:
type(env.observation_space.low)

numpy.ndarray

In [25]:
ll = env.observation_space.low

In [29]:
q = [l for l in ll]
q

[-2.3999999999999999, -inf, -0.20943951023931953, -inf]

In [30]:
qq = q[1]

In [36]:
type(qq)

numpy.float64

In [37]:
type(float(qq))

float

In [48]:
for i in range(200):
    env.step(1)
    print str(env.state)
    env.render()
env.render(close=True)

(5263.2009758580689, 308.49734499454803, -417.7618886327341, -19.036673752012227)
(5269.3709227579602, 308.66670120199825, -418.14262210777434, -18.803804330929051)
(5275.544256782, 308.96942255492377, -418.51869819439293, -18.281566642910146)
(5281.7236452330981, 309.36665387053944, -418.88432952725111, -17.634406642308807)
(5287.9109783105087, 309.80716815094644, -419.23701766009731, -17.051675342538488)
(5294.1071216735272, 310.25269537505119, -419.57805116694806, -16.651532562416872)
(5300.312175581028, 310.68130509533944, -419.91108181819641, -16.474255187220638)
(5306.5258016829348, 311.07938897978948, -420.2405669219408, -16.508149627295207)
(5312.7473894625309, 311.43364458784356, -420.57072991448672, -16.706428913630397)
(5318.9760623542879, 311.72700990269834, -420.90485849275933, -16.996062416314548)
(5325.2106025523417, 311.94038412659285, -421.24477974108561, -17.295231891956302)
(5331.4494102348735, 312.0603552032315, -421.59068437892472, -17.547408701104981)
(5337.690617

In [40]:
env.reset()

array([-0.02835772,  0.02703084,  0.04572492,  0.01954563])